# -*- coding: utf-8 -*-
"""US states (50 + DC) and major cities for GasRadar SEO pages."""

STATES = [
    {"slug": "alabama", "code": "AL", "name_es": "Alabama", "name_en": "Alabama", "band": "bajo",
     "note_es": "Suele estar por debajo del promedio nacional. I-65 e I-20 concentran truck stops baratos.",
     "note_en": "Usually below the national average. I-65 and I-20 are packed with cheap truck stops.",
     "brands": "Murphy, Racetrac, Costco, Sam’s", "neighbors": ["mississippi", "tennessee", "georgia", "florida"]},
    {"slug": "alaska", "code": "AK", "name_es": "Alaska", "name_en": "Alaska", "band": "alto",
     "note_es": "El flete y el clima suben el precio. Anchorage es más barato que pueblos remotos.",
     "note_en": "Freight and climate push prices up. Anchorage is cheaper than remote towns.",
     "brands": "Holiday, Tesoro, Costco", "neighbors": []},
    {"slug": "arizona", "code": "AZ", "name_es": "Arizona", "name_en": "Arizona", "band": "medio",
     "note_es": "Phoenix y Tucson se mueven con el calor del verano. Evita el aeropuerto PHX y Scottsdale.",
     "note_en": "Phoenix and Tucson swing with summer heat. Skip PHX airport and Scottsdale if you can.",
     "brands": "QuikTrip, Costco, Circle K, Fry’s", "neighbors": ["california", "nevada", "utah", "new-mexico"]},
    {"slug": "arkansas", "code": "AR", "name_es": "Arkansas", "name_en": "Arkansas", "band": "bajo",
     "note_es": "Impuesto estatal bajo. Little Rock e I-40 suelen tener buenas marcas de descuento.",
     "note_en": "Low state tax. Little Rock and I-40 often have solid discount brands.",
     "brands": "Murphy, Kum & Go, Sam’s", "neighbors": ["texas", "oklahoma", "missouri", "tennessee", "mississippi", "louisiana"]},
    {"slug": "california", "code": "CA", "name_es": "California", "name_en": "California", "band": "alto",
     "note_es": "La más cara del país: impuesto alto y gasolina CARB. Compara siempre el ZIP del barrio, no solo la ciudad.",
     "note_en": "The priciest state: high tax plus CARB fuel. Compare the neighborhood ZIP, not just the city.",
     "brands": "Costco, Arco, Chevron, 76", "neighbors": ["oregon", "nevada", "arizona"]},
    {"slug": "colorado", "code": "CO", "name_es": "Colorado", "name_en": "Colorado", "band": "medio",
     "note_es": "Denver y Colorado Springs cambian por barrio. DIA y downtown suelen ser más caros que Aurora o Lakewood.",
     "note_en": "Denver and Colorado Springs change by neighborhood. DIA and downtown are often pricier than Aurora or Lakewood.",
     "brands": "King Soopers, Costco, Loaf ’N Jug, Conoco", "neighbors": ["wyoming", "nebraska", "kansas", "oklahoma", "new-mexico", "utah"]},
    {"slug": "connecticut", "code": "CT", "name_es": "Connecticut", "name_en": "Connecticut", "band": "alto",
     "note_es": "New England es caro. Evita I-95 cerca de NYC; los suburbios interiores suelen mejorar.",
     "note_en": "New England runs expensive. Avoid I-95 near NYC; inland suburbs are often better.",
     "brands": "Costco, Stop & Shop, Mobil", "neighbors": ["new-york", "massachusetts", "rhode-island"]},
    {"slug": "delaware", "code": "DE", "name_es": "Delaware", "name_en": "Delaware", "band": "medio",
     "note_es": "Estado pequeño: cruza a Maryland o Jersey si el ZIP de Wilmington no convence.",
     "note_en": "Tiny state: hop to Maryland or Jersey if Wilmington’s ZIP isn’t worth it.",
     "brands": "Wawa, Costco, Royal Farms", "neighbors": ["maryland", "new-jersey", "pennsylvania"]},
    {"slug": "washington-dc", "code": "DC", "name_es": "Washington D.C.", "name_en": "Washington, D.C.", "band": "alto",
     "note_es": "Urbano y caro. Vale más buscar en Maryland o Virginia (Arlington, Alexandria, Silver Spring).",
     "note_en": "Urban and expensive. It’s often worth checking Maryland or Virginia (Arlington, Alexandria, Silver Spring).",
     "brands": "Costco, Sheetz, Wawa", "neighbors": ["maryland", "virginia"]},
    {"slug": "florida", "code": "FL", "name_es": "Florida", "name_en": "Florida", "band": "medio",
     "note_es": "La costa turística (Miami Beach, Orlando resorts) es más cara que el interior. El I-4 y el I-95 cambian mucho.",
     "note_en": "Tourist coasts (Miami Beach, Orlando resorts) cost more than inland. I-4 and I-95 swing a lot.",
     "brands": "Costco, Racetrac, Wawa, 7-Eleven", "neighbors": ["georgia", "alabama"]},
    {"slug": "georgia", "code": "GA", "name_es": "Georgia", "name_en": "Georgia", "band": "medio",
     "note_es": "Atlanta downtown y Hartsfield-Jackson suelen ser más caros que los suburbios (Marietta, Decatur).",
     "note_en": "Downtown Atlanta and Hartsfield-Jackson are usually pricier than suburbs (Marietta, Decatur).",
     "brands": "QuikTrip, Racetrac, Costco, Kroger", "neighbors": ["florida", "alabama", "tennessee", "north-carolina", "south-carolina"]},
    {"slug": "hawaii", "code": "HI", "name_es": "Hawái", "name_en": "Hawaii", "band": "alto",
     "note_es": "Islas: casi todo llega en barco. Honolulu es más barato que Maui o el Big Island.",
     "note_en": "Islands: almost everything is shipped. Honolulu is cheaper than Maui or the Big Island.",
     "brands": "Costco, Safeway, Aloha", "neighbors": []},
    {"slug": "idaho", "code": "ID", "name_es": "Idaho", "name_en": "Idaho", "band": "bajo",
     "note_es": "Boise y I-84 suelen estar por debajo del promedio del Oeste. Maverik y Costco compiten bien.",
     "note_en": "Boise and I-84 often sit below the Western average. Maverik and Costco compete hard.",
     "brands": "Maverik, Costco, Stinker", "neighbors": ["washington", "oregon", "nevada", "utah", "wyoming", "montana"]},
    {"slug": "illinois", "code": "IL", "name_es": "Illinois", "name_en": "Illinois", "band": "alto",
     "note_es": "Chicago y los impuestos del condado suben el precio. Downstate (Springfield, Champaign) suele ser más barato.",
     "note_en": "Chicago and county taxes lift the price. Downstate (Springfield, Champaign) is usually cheaper.",
     "brands": "Costco, Thorntons, BP, Marathon", "neighbors": ["wisconsin", "indiana", "kentucky", "missouri", "iowa"]},
    {"slug": "indiana", "code": "IN", "name_es": "Indiana", "name_en": "Indiana", "band": "medio",
     "note_es": "Indianapolis e I-65/I-70 tienen mucha competencia. Evita solo el aeropuerto IND.",
     "note_en": "Indianapolis and I-65/I-70 have lots of competition. Just skip IND airport.",
     "brands": "Speedway, Thorntons, Costco, Kroger", "neighbors": ["illinois", "michigan", "ohio", "kentucky"]},
    {"slug": "iowa", "code": "IA", "name_es": "Iowa", "name_en": "Iowa", "band": "bajo",
     "note_es": "I-80 es un corredor de truck stops. Des Moines y Cedar Rapids suelen estar por debajo del promedio.",
     "note_en": "I-80 is a truck-stop corridor. Des Moines and Cedar Rapids usually sit below average.",
     "brands": "Kum & Go, Casey’s, Costco", "neighbors": ["minnesota", "wisconsin", "illinois", "missouri", "nebraska", "south-dakota"]},
    {"slug": "kansas", "code": "KS", "name_es": "Kansas", "name_en": "Kansas", "band": "bajo",
     "note_es": "Wichita y Kansas City (lado KS) suelen ser baratos. I-70 es bueno para road trips.",
     "note_en": "Wichita and Kansas City (KS side) are usually cheap. I-70 is solid for road trips.",
     "brands": "QuikTrip, Casey’s, Phillips 66", "neighbors": ["missouri", "oklahoma", "colorado", "nebraska"]},
    {"slug": "kentucky", "code": "KY", "name_es": "Kentucky", "name_en": "Kentucky", "band": "bajo",
     "note_es": "Louisville y Lexington tienen buena competencia. I-65 e I-75 bajan el precio en truck stops.",
     "note_en": "Louisville and Lexington have solid competition. I-65 and I-75 truck stops drop the price.",
     "brands": "Thorntons, Speedway, Kroger, Costco", "neighbors": ["ohio", "indiana", "illinois", "missouri", "tennessee", "virginia", "west-virginia"]},
    {"slug": "louisiana", "code": "LA", "name_es": "Luisiana", "name_en": "Louisiana", "band": "bajo",
     "note_es": "Cerca de las refinerías el Regular suele ser barato. New Orleans turístico es más caro que Baton Rouge.",
     "note_en": "Near the refineries Regular is often cheap. Tourist New Orleans costs more than Baton Rouge.",
     "brands": "Racetrac, Murphy, Costco", "neighbors": ["texas", "arkansas", "mississippi"]},
    {"slug": "maine", "code": "ME", "name_es": "Maine", "name_en": "Maine", "band": "alto",
     "note_es": "Nueva Inglaterra + turismo costero. Portland es más caro que el interior (Lewiston, Augusta).",
     "note_en": "New England plus coastal tourism. Portland is pricier than inland (Lewiston, Augusta).",
     "brands": "Irving, Cumberland Farms, Costco", "neighbors": ["new-hampshire"]},
    {"slug": "maryland", "code": "MD", "name_es": "Maryland", "name_en": "Maryland", "band": "alto",
     "note_es": "Baltimore y el área de D.C. son caros. Wawa y Costco en los suburbios suelen ganar.",
     "note_en": "Baltimore and the D.C. suburbs run expensive. Wawa and Costco in the suburbs usually win.",
     "brands": "Wawa, Costco, Royal Farms, Sheetz", "neighbors": ["pennsylvania", "delaware", "virginia", "washington-dc", "west-virginia"]},
    {"slug": "massachusetts", "code": "MA", "name_es": "Massachusetts", "name_en": "Massachusetts", "band": "alto",
     "note_es": "Boston downtown es caro. Busca en Quincy, Waltham o al otro lado del río.",
     "note_en": "Downtown Boston is expensive. Check Quincy, Waltham, or across the river.",
     "brands": "Costco, Stop & Shop, Mobil, Shell", "neighbors": ["rhode-island", "connecticut", "new-york", "new-hampshire", "vermont"]},
    {"slug": "michigan", "code": "MI", "name_es": "Míchigan", "name_en": "Michigan", "band": "medio",
     "note_es": "Detroit y los impuestos locales cambian el precio. Grand Rapids y I-94 suelen ser más suaves.",
     "note_en": "Detroit and local taxes swing the price. Grand Rapids and I-94 are often gentler.",
     "brands": "Speedway, Costco, Meijer, Marathon", "neighbors": ["ohio", "indiana", "wisconsin"]},
    {"slug": "minnesota", "code": "MN", "name_es": "Minnesota", "name_en": "Minnesota", "band": "medio",
     "note_es": "Minneapolis–Saint Paul: evita el aeropuerto MSP. Costco y Holiday compiten en los suburbios.",
     "note_en": "Minneapolis–Saint Paul: skip MSP airport. Costco and Holiday compete in the suburbs.",
     "brands": "Holiday, Costco, Kwik Trip", "neighbors": ["wisconsin", "iowa", "south-dakota", "north-dakota"]},
    {"slug": "mississippi", "code": "MS", "name_es": "Misisipi", "name_en": "Mississippi", "band": "bajo",
     "note_es": "De los más baratos del Sur. Jackson e I-55/I-20 tienen Murphy y Racetrac fuertes.",
     "note_en": "Among the cheapest in the South. Jackson and I-55/I-20 have strong Murphy and Racetrac.",
     "brands": "Murphy, Racetrac, Chevron", "neighbors": ["alabama", "tennessee", "arkansas", "louisiana"]},
    {"slug": "missouri", "code": "MO", "name_es": "Misuri", "name_en": "Missouri", "band": "bajo",
     "note_es": "Kansas City y St. Louis tienen mucha competencia. I-70 es un corredor barato.",
     "note_en": "Kansas City and St. Louis have plenty of competition. I-70 is a cheap corridor.",
     "brands": "QuikTrip, Casey’s, Costco", "neighbors": ["iowa", "illinois", "kentucky", "tennessee", "arkansas", "oklahoma", "kansas", "nebraska"]},
    {"slug": "montana", "code": "MT", "name_es": "Montana", "name_en": "Montana", "band": "medio",
     "note_es": "Billings y I-90 son lo más estable. Pueblos de montaña y turismo de verano suben el precio.",
     "note_en": "Billings and I-90 are the most stable. Mountain towns and summer tourism lift the price.",
     "brands": "Town Pump, Costco, Cenex", "neighbors": ["idaho", "wyoming", "north-dakota", "south-dakota"]},
    {"slug": "nebraska", "code": "NE", "name_es": "Nebraska", "name_en": "Nebraska", "band": "bajo",
     "note_es": "Omaha e I-80 suelen estar baratos. Los truck stops ganan a las estaciones del centro.",
     "note_en": "Omaha and I-80 are usually cheap. Truck stops beat downtown stations.",
     "brands": "Buc-ee’s (cerca), Casey’s, Costco", "neighbors": ["south-dakota", "iowa", "missouri", "kansas", "colorado", "wyoming"]},
    {"slug": "nevada", "code": "NV", "name_es": "Nevada", "name_en": "Nevada", "band": "medio",
     "note_es": "El Strip de Las Vegas es caro. Busca en Henderson o North Las Vegas. Reno es otro mercado.",
     "note_en": "The Las Vegas Strip is expensive. Check Henderson or North Las Vegas. Reno is a separate market.",
     "brands": "Costco, Terrible’s, Maverik, Smith’s", "neighbors": ["california", "oregon", "idaho", "utah", "arizona"]},
    {"slug": "new-hampshire", "code": "NH", "name_es": "Nuevo Hampshire", "name_en": "New Hampshire", "band": "medio",
     "note_es": "Sin impuesto estatal de ventas, pero la gasolina no siempre es la más barata de New England.",
     "note_en": "No state sales tax, but gas still isn’t always New England’s cheapest.",
     "brands": "Irving, Costco, Cumberland Farms", "neighbors": ["maine", "massachusetts", "vermont"]},
    {"slug": "new-jersey", "code": "NJ", "name_es": "Nueva Jersey", "name_en": "New Jersey", "band": "alto",
     "note_es": "Sin self-service: alguien carga por ti. Wawa y Costco en los suburbios suelen ganar a Newark o el Turnpike.",
     "note_en": "No self-serve: an attendant pumps for you. Suburban Wawa and Costco usually beat Newark or the Turnpike.",
     "brands": "Wawa, Costco, Lukoil, Exxon", "neighbors": ["new-york", "pennsylvania", "delaware"]},
    {"slug": "new-mexico", "code": "NM", "name_es": "Nuevo México", "name_en": "New Mexico", "band": "bajo",
     "note_es": "Albuquerque e I-40 suelen estar por debajo del Oeste. Santa Fe turístico es más caro.",
     "note_en": "Albuquerque and I-40 usually sit below the Western average. Tourist Santa Fe is pricier.",
     "brands": "Costco, Murphy, Phillips 66", "neighbors": ["texas", "oklahoma", "colorado", "arizona", "utah"]},
    {"slug": "new-york", "code": "NY", "name_es": "Nueva York", "name_en": "New York", "band": "alto",
     "note_es": "NYC y Long Island son carísimos. Upstate (Buffalo, Rochester, Albany) cambia el juego.",
     "note_en": "NYC and Long Island are very expensive. Upstate (Buffalo, Rochester, Albany) is a different market.",
     "brands": "Costco, Speedway, Mobil, Sunoco", "neighbors": ["pennsylvania", "new-jersey", "connecticut", "massachusetts", "vermont"]},
    {"slug": "north-carolina", "code": "NC", "name_es": "Carolina del Norte", "name_en": "North Carolina", "band": "medio",
     "note_es": "Charlotte y Raleigh tienen buena competencia. Evita el aeropuerto CLT y el downtown.",
     "note_en": "Charlotte and Raleigh have solid competition. Skip CLT airport and downtown.",
     "brands": "Sheetz, Costco, Racetrac, Circle K", "neighbors": ["virginia", "tennessee", "georgia", "south-carolina"]},
    {"slug": "north-dakota", "code": "ND", "name_es": "Dakota del Norte", "name_en": "North Dakota", "band": "medio",
     "note_es": "Fargo e I-94 son lo más predecible. Zonas petroleras del oeste pueden saltar de precio.",
     "note_en": "Fargo and I-94 are the most predictable. Western oil-patch towns can spike.",
     "brands": "Cenex, Costco, Holiday", "neighbors": ["minnesota", "south-dakota", "montana"]},
    {"slug": "ohio", "code": "OH", "name_es": "Ohio", "name_en": "Ohio", "band": "medio",
     "note_es": "Columbus, Cleveland y Cincinnati: los suburbios ganan al centro. I-71 e I-75 tienen competencia.",
     "note_en": "Columbus, Cleveland, Cincinnati: suburbs beat downtown. I-71 and I-75 have competition.",
     "brands": "Speedway, GetGo, Costco, Kroger", "neighbors": ["pennsylvania", "west-virginia", "kentucky", "indiana", "michigan"]},
    {"slug": "oklahoma", "code": "OK", "name_es": "Oklahoma", "name_en": "Oklahoma", "band": "bajo",
     "note_es": "De los más baratos del país. Oklahoma City y Tulsa tienen QuikTrip en cada esquina.",
     "note_en": "Among the cheapest in the country. Oklahoma City and Tulsa have QuikTrip on every corner.",
     "brands": "QuikTrip, Love’s, Costco", "neighbors": ["texas", "arkansas", "missouri", "kansas", "colorado", "new-mexico"]},
    {"slug": "oregon", "code": "OR", "name_es": "Oregón", "name_en": "Oregon", "band": "alto",
     "note_es": "Impuesto alto y, en casi todo el estado, no hay self-service. Portland es más caro que Salem o Eugene.",
     "note_en": "High tax, and almost no self-serve. Portland is pricier than Salem or Eugene.",
     "brands": "Costco, Fred Meyer, Chevron", "neighbors": ["washington", "idaho", "nevada", "california"]},
    {"slug": "pennsylvania", "code": "PA", "name_es": "Pensilvania", "name_en": "Pennsylvania", "band": "alto",
     "note_es": "Impuesto alto. Filadelfia y Pittsburgh: Sheetz y Costco en los suburbios suelen ganar.",
     "note_en": "High tax. Philadelphia and Pittsburgh: suburban Sheetz and Costco usually win.",
     "brands": "Sheetz, Wawa, Costco, GetGo", "neighbors": ["new-york", "new-jersey", "delaware", "maryland", "west-virginia", "ohio"]},
    {"slug": "rhode-island", "code": "RI", "name_es": "Rhode Island", "name_en": "Rhode Island", "band": "alto",
     "note_es": "Estado chico y caro. A veces conviene cruzar a Massachusetts con el mismo tanque.",
     "note_en": "Small and expensive. Sometimes it’s worth crossing into Massachusetts on the same tank.",
     "brands": "Costco, Stop & Shop, Mobil", "neighbors": ["connecticut", "massachusetts"]},
    {"slug": "south-carolina", "code": "SC", "name_es": "Carolina del Sur", "name_en": "South Carolina", "band": "bajo",
     "note_es": "Columbia, Greenville y Charleston: el turismo de playa sube el precio; el interior es más barato.",
     "note_en": "Columbia, Greenville, Charleston: beach tourism lifts the price; inland is cheaper.",
     "brands": "QuikTrip, Racetrac, Costco, Circle K", "neighbors": ["north-carolina", "georgia"]},
    {"slug": "south-dakota", "code": "SD", "name_es": "Dakota del Sur", "name_en": "South Dakota", "band": "bajo",
     "note_es": "Sioux Falls e I-90 suelen estar baratos. El turismo de Black Hills sube el precio en verano.",
     "note_en": "Sioux Falls and I-90 are usually cheap. Black Hills tourism lifts summer prices.",
     "brands": "Casey’s, Costco, Cenex", "neighbors": ["north-dakota", "minnesota", "iowa", "nebraska", "wyoming", "montana"]},
    {"slug": "tennessee", "code": "TN", "name_es": "Tennessee", "name_en": "Tennessee", "band": "bajo",
     "note_es": "Nashville y Memphis tienen mucha competencia. Evita solo downtown y el aeropuerto.",
     "note_en": "Nashville and Memphis have lots of competition. Just skip downtown and the airport.",
     "brands": "QuikTrip, Mapco, Costco, Kroger", "neighbors": ["kentucky", "virginia", "north-carolina", "georgia", "alabama", "mississippi", "arkansas", "missouri"]},
    {"slug": "texas", "code": "TX", "name_es": "Texas", "name_en": "Texas", "band": "bajo",
     "note_es": "Impuesto bajo y mucho suministro. Houston, Dallas, San Antonio y El Paso son mercados distintos: usa el ZIP del barrio.",
     "note_en": "Low tax and lots of supply. Houston, Dallas, San Antonio, and El Paso are different markets—use the neighborhood ZIP.",
     "brands": "Costco, QuikTrip, Racetrac, Buc-ee’s, H-E-B", "neighbors": ["new-mexico", "oklahoma", "arkansas", "louisiana"]},
    {"slug": "utah", "code": "UT", "name_es": "Utah", "name_en": "Utah", "band": "medio",
     "note_es": "Salt Lake City e I-15 son lo más estable. Parques y ski resorts suben el precio.",
     "note_en": "Salt Lake City and I-15 are the most stable. Parks and ski resorts lift the price.",
     "brands": "Maverik, Costco, Smith’s", "neighbors": ["idaho", "wyoming", "colorado", "arizona", "nevada"]},
    {"slug": "vermont", "code": "VT", "name_es": "Vermont", "name_en": "Vermont", "band": "alto",
     "note_es": "Rural y caro. Burlington es lo más competitivo; evite pueblos de ski en temporada.",
     "note_en": "Rural and expensive. Burlington is the most competitive; skip ski towns in season.",
     "brands": "Costco, Maplefields, Mobil", "neighbors": ["new-york", "new-hampshire", "massachusetts"]},
    {"slug": "virginia", "code": "VA", "name_es": "Virginia", "name_en": "Virginia", "band": "medio",
     "note_es": "Northern Virginia (cerca de D.C.) es caro. Richmond y Virginia Beach son otro mercado.",
     "note_en": "Northern Virginia (near D.C.) is expensive. Richmond and Virginia Beach are a different market.",
     "brands": "Sheetz, Wawa, Costco, Kroger", "neighbors": ["maryland", "washington-dc", "north-carolina", "tennessee", "kentucky", "west-virginia"]},
    {"slug": "washington", "code": "WA", "name_es": "Washington", "name_en": "Washington", "band": "alto",
     "note_es": "Impuesto alto. Seattle es caro; Spokane y el este del estado suelen estar mejor.",
     "note_en": "High tax. Seattle is expensive; Spokane and eastern Washington are usually better.",
     "brands": "Costco, Fred Meyer, Safeway, 76", "neighbors": ["oregon", "idaho"]},
    {"slug": "west-virginia", "code": "WV", "name_es": "Virginia Occidental", "name_en": "West Virginia", "band": "medio",
     "note_es": "Charleston e I-77/I-79. Sheetz suele ser la referencia en el estado.",
     "note_en": "Charleston and I-77/I-79. Sheetz is often the state’s benchmark.",
     "brands": "Sheetz, Speedway, Go-Mart", "neighbors": ["ohio", "pennsylvania", "maryland", "virginia", "kentucky"]},
    {"slug": "wisconsin", "code": "WI", "name_es": "Wisconsin", "name_en": "Wisconsin", "band": "medio",
     "note_es": "Milwaukee y Madison: Kwik Trip suele ganar. Evita el downtown y el aeropuerto MKE.",
     "note_en": "Milwaukee and Madison: Kwik Trip usually wins. Skip downtown and MKE airport.",
     "brands": "Kwik Trip, Costco, Mobil, PDQ", "neighbors": ["minnesota", "iowa", "illinois", "michigan"]},
    {"slug": "wyoming", "code": "WY", "name_es": "Wyoming", "name_en": "Wyoming", "band": "bajo",
     "note_es": "Cheyenne e I-80/I-25 suelen ser baratos. Jackson y el turismo de parques suben el precio.",
     "note_en": "Cheyenne and I-80/I-25 are usually cheap. Jackson and park tourism lift the price.",
     "brands": "Maverik, Love’s, Sinclair", "neighbors": ["montana", "south-dakota", "nebraska", "colorado", "utah", "idaho"]},
]

CITIES = [
    {"slug": "birmingham", "name": "Birmingham", "state": "alabama", "zip": "35203", "nearby": "Hoover, Vestavia Hills",
     "tip_es": "El centro es más caro que Hoover. I-65 tiene Murphy y Racetrac fuertes.",
     "tip_en": "Downtown is pricier than Hoover. I-65 has strong Murphy and Racetrac."},
    {"slug": "montgomery", "name": "Montgomery", "state": "alabama", "zip": "36104", "nearby": "Prattville",
     "tip_es": "Capital chica: compara 2–3 millas y casi siempre hay un Murphy más barato.",
     "tip_en": "Small capital: compare 2–3 miles and there’s almost always a cheaper Murphy."},
    {"slug": "mobile", "name": "Mobile", "state": "alabama", "zip": "36602", "nearby": "Daphne, Spanish Fort",
     "tip_es": "El puerto y I-10 mueven el precio. El lado este de la bahía suele estar mejor.",
     "tip_en": "The port and I-10 move the price. The east side of the bay is often better."},
    {"slug": "huntsville", "name": "Huntsville", "state": "alabama", "zip": "35801", "nearby": "Madison",
     "tip_es": "Madison suele ganar al centro. Evita las estaciones pegadas a Redstone.",
     "tip_en": "Madison usually beats downtown. Skip stations next to Redstone."},
    {"slug": "anchorage", "name": "Anchorage", "state": "alaska", "zip": "99501", "nearby": "Eagle River",
     "tip_es": "Lo más barato de Alaska. Costco y las grandes avenidas ganan a los barrios turísticos.",
     "tip_en": "Alaska’s cheapest major market. Costco and big corridors beat tourist blocks."},
    {"slug": "phoenix", "name": "Phoenix", "state": "arizona", "zip": "85004", "nearby": "Mesa, Glendale, Tempe",
     "tip_es": "Evita PHX y Scottsdale. Mesa, Glendale y el oeste suelen estar 15–30¢ más baratos.",
     "tip_en": "Skip PHX and Scottsdale. Mesa, Glendale, and the west side are often 15–30¢ cheaper."},
    {"slug": "tucson", "name": "Tucson", "state": "arizona", "zip": "85701", "nearby": "Oro Valley, Marana",
     "tip_es": "El centro y la universidad suben el precio. Costco y Circle K en el norte suelen ganar.",
     "tip_en": "Downtown and the university lift the price. Costco and Circle K in the north usually win."},
    {"slug": "mesa", "name": "Mesa", "state": "arizona", "zip": "85201", "nearby": "Phoenix, Gilbert",
     "tip_es": "Uno de los ZIP más competitivos del Valle. Compara 5 millas y listo.",
     "tip_en": "One of the Valley’s most competitive ZIPs. Compare 5 miles and you’re done."},
    {"slug": "little-rock", "name": "Little Rock", "state": "arkansas", "zip": "72201", "nearby": "North Little Rock",
     "tip_es": "Cruza el río a North Little Rock si el centro no convence.",
     "tip_en": "Cross the river to North Little Rock if downtown isn’t worth it."},
    {"slug": "los-angeles", "name": "Los Angeles", "state": "california", "zip": "90012", "nearby": "Long Beach, Pasadena, Glendale",
     "tip_es": "LA no es un solo precio: Koreatown, el Valle y Long Beach cambian 20–40¢. Usa el ZIP del barrio.",
     "tip_en": "LA is not one price: Koreatown, the Valley, and Long Beach can swing 20–40¢. Use the neighborhood ZIP."},
    {"slug": "san-diego", "name": "San Diego", "state": "california", "zip": "92101", "nearby": "Chula Vista, El Cajon",
     "tip_es": "Downtown y la playa son caros. Chula Vista y El Cajon suelen estar mejor.",
     "tip_en": "Downtown and the beach are expensive. Chula Vista and El Cajon are usually better."},
    {"slug": "san-jose", "name": "San Jose", "state": "california", "zip": "95113", "nearby": "Sunnyvale, Fremont",
     "tip_es": "Silicon Valley es caro. Compara Fremont o el sur de San José, no solo downtown.",
     "tip_en": "Silicon Valley is expensive. Compare Fremont or south San Jose, not just downtown."},
    {"slug": "san-francisco", "name": "San Francisco", "state": "california", "zip": "94103", "nearby": "Daly City, Oakland",
     "tip_es": "De las más caras del país. A veces sale más barato cargar en Daly City u Oakland.",
     "tip_en": "Among the priciest in the country. Sometimes it’s cheaper to fill in Daly City or Oakland."},
    {"slug": "sacramento", "name": "Sacramento", "state": "california", "zip": "95814", "nearby": "Elk Grove, Roseville",
     "tip_es": "Más barato que la Bahía. Elk Grove y Roseville suelen ganar al centro.",
     "tip_en": "Cheaper than the Bay Area. Elk Grove and Roseville usually beat downtown."},
    {"slug": "fresno", "name": "Fresno", "state": "california", "zip": "93721", "nearby": "Clovis",
     "tip_es": "El Valle Central está por debajo de LA o SF. Clovis y el norte de Fresno compiten bien.",
     "tip_en": "The Central Valley sits below LA or SF. Clovis and north Fresno compete well."},
    {"slug": "bakersfield", "name": "Bakersfield", "state": "california", "zip": "93301", "nearby": "Delano",
     "tip_es": "De las más baratas de California por las refinerías cercanas. Arco y Costco mandan.",
     "tip_en": "Among California’s cheapest thanks to nearby refining. Arco and Costco lead."},
    {"slug": "denver", "name": "Denver", "state": "colorado", "zip": "80202", "nearby": "Aurora, Lakewood, Thornton",
     "tip_es": "Downtown y RiNo son caros. Aurora, Lakewood y Thornton suelen estar 10–25¢ más baratos.",
     "tip_en": "Downtown and RiNo are expensive. Aurora, Lakewood, and Thornton are often 10–25¢ cheaper."},
    {"slug": "colorado-springs", "name": "Colorado Springs", "state": "colorado", "zip": "80907", "nearby": "Fountain, Monument",
     "tip_es": "El 80907 y el norte de la ciudad suelen estar mejor que el centro o Academy cerca de la Base.",
     "tip_en": "80907 and the north side usually beat downtown or Academy near the Base."},
    {"slug": "aurora", "name": "Aurora", "state": "colorado", "zip": "80012", "nearby": "Denver, Centennial",
     "tip_es": "Uno de los ZIP más buscados del metro Denver. King Soopers y Costco mandan.",
     "tip_en": "One of metro Denver’s most-searched ZIPs. King Soopers and Costco lead."},
    {"slug": "hartford", "name": "Hartford", "state": "connecticut", "zip": "06103", "nearby": "West Hartford, New Britain",
     "tip_es": "West Hartford y New Britain suelen ganar al centro.",
     "tip_en": "West Hartford and New Britain usually beat downtown."},
    {"slug": "wilmington", "name": "Wilmington", "state": "delaware", "zip": "19801", "nearby": "Newark DE",
     "tip_es": "Estado chico: si no hay oferta, cruza a Maryland en 15 minutos.",
     "tip_en": "Tiny state: if the price isn’t there, Maryland is 15 minutes away."},
    {"slug": "washington", "name": "Washington", "state": "washington-dc", "zip": "20001", "nearby": "Arlington, Silver Spring",
     "tip_es": "Carga en Arlington, Alexandria o Silver Spring. Dentro del Distrito casi siempre es más caro.",
     "tip_en": "Fill in Arlington, Alexandria, or Silver Spring. Inside the District is almost always pricier."},
    {"slug": "miami", "name": "Miami", "state": "florida", "zip": "33130", "nearby": "Hialeah, Doral, Homestead",
     "tip_es": "Miami Beach y Brickell son caros. Hialeah, Doral y el sur suelen estar mejor.",
     "tip_en": "Miami Beach and Brickell are expensive. Hialeah, Doral, and the south side are usually better."},
    {"slug": "orlando", "name": "Orlando", "state": "florida", "zip": "32801", "nearby": "Kissimmee, Sanford",
     "tip_es": "Los resorts e I-Drive son una trampa. Kissimmee y el este suelen estar más baratos.",
     "tip_en": "Resorts and I-Drive are a trap. Kissimmee and the east side are usually cheaper."},
    {"slug": "tampa", "name": "Tampa", "state": "florida", "zip": "33602", "nearby": "St. Petersburg, Brandon",
     "tip_es": "Downtown y el aeropuerto TPA suben el precio. Brandon y St. Pete tienen más competencia.",
     "tip_en": "Downtown and TPA lift the price. Brandon and St. Pete have more competition."},
    {"slug": "jacksonville", "name": "Jacksonville", "state": "florida", "zip": "32202", "nearby": "Orange Park",
     "tip_es": "Ciudad enorme: el ZIP importa más que el nombre. Orange Park suele estar mejor que el centro.",
     "tip_en": "Huge city: ZIP matters more than the name. Orange Park often beats downtown."},
    {"slug": "atlanta", "name": "Atlanta", "state": "georgia", "zip": "30303", "nearby": "Marietta, Decatur, Sandy Springs",
     "tip_es": "Downtown y Hartsfield-Jackson son caros. Marietta y Decatur suelen ganar.",
     "tip_en": "Downtown and Hartsfield-Jackson are expensive. Marietta and Decatur usually win."},
    {"slug": "honolulu", "name": "Honolulu", "state": "hawaii", "zip": "96813", "nearby": "Kapolei, Pearl City",
     "tip_es": "Waikiki es caro. Kapolei y Pearl City suelen estar mejor, Costco manda.",
     "tip_en": "Waikiki is expensive. Kapolei and Pearl City are usually better; Costco leads."},
    {"slug": "boise", "name": "Boise", "state": "idaho", "zip": "83702", "nearby": "Meridian, Nampa",
     "tip_es": "Meridian y Nampa suelen estar 5–15¢ bajo el centro de Boise.",
     "tip_en": "Meridian and Nampa are often 5–15¢ under downtown Boise."},
    {"slug": "chicago", "name": "Chicago", "state": "illinois", "zip": "60601", "nearby": "Cicero, Naperville, Joliet",
     "tip_es": "The Loop y O’Hare son caros. Cicero, Berwyn o los suburbios del sur suelen estar mejor.",
     "tip_en": "The Loop and O’Hare are expensive. Cicero, Berwyn, or the south suburbs are usually better."},
    {"slug": "indianapolis", "name": "Indianapolis", "state": "indiana", "zip": "46204", "nearby": "Carmel, Greenwood",
     "tip_es": "El Speedway y el aeropuerto IND suben el precio. Greenwood y el este suelen ganar.",
     "tip_en": "The Speedway and IND airport lift the price. Greenwood and the east side usually win."},
    {"slug": "des-moines", "name": "Des Moines", "state": "iowa", "zip": "50309", "nearby": "West Des Moines, Ankeny",
     "tip_es": "West Des Moines y Ankeny suelen estar mejor que el downtown.",
     "tip_en": "West Des Moines and Ankeny usually beat downtown."},
    {"slug": "wichita", "name": "Wichita", "state": "kansas", "zip": "67202", "nearby": "Derby",
     "tip_es": "QuikTrip manda. Compara 3 millas y casi siempre hay un QT más barato.",
     "tip_en": "QuikTrip leads. Compare 3 miles and there’s almost always a cheaper QT."},
    {"slug": "kansas-city-ks", "name": "Kansas City", "state": "kansas", "zip": "66101", "nearby": "Overland Park, Olathe",
     "tip_es": "El lado de Kansas suele estar mejor que el downtown de Missouri. Overland Park compite fuerte.",
     "tip_en": "The Kansas side is often better than Missouri downtown. Overland Park competes hard."},
    {"slug": "louisville", "name": "Louisville", "state": "kentucky", "zip": "40202", "nearby": "Jeffersontown",
     "tip_es": "Evita el aeropuerto SDF. El este de la ciudad suele estar más barato.",
     "tip_en": "Skip SDF airport. The east side is usually cheaper."},
    {"slug": "lexington", "name": "Lexington", "state": "kentucky", "zip": "40507", "nearby": "Nicholasville",
     "tip_es": "Universidad y turismo de caballos suben el centro. Nicholasville suele ganar.",
     "tip_en": "Campus and horse-country tourism lift downtown. Nicholasville usually wins."},
    {"slug": "new-orleans", "name": "New Orleans", "state": "louisiana", "zip": "70112", "nearby": "Metairie, Kenner",
     "tip_es": "El French Quarter es una trampa. Metairie y Kenner suelen estar mucho mejor.",
     "tip_en": "The French Quarter is a trap. Metairie and Kenner are usually much better."},
    {"slug": "baton-rouge", "name": "Baton Rouge", "state": "louisiana", "zip": "70802", "nearby": "Gonzales",
     "tip_es": "Cerca de las refinerías: Regular suele estar por debajo de New Orleans.",
     "tip_en": "Near the refineries: Regular is usually below New Orleans."},
    {"slug": "portland-me", "name": "Portland", "state": "maine", "zip": "04101", "nearby": "South Portland, Westbrook",
     "tip_es": "La costa es cara. South Portland y Westbrook suelen estar mejor.",
     "tip_en": "The coast is expensive. South Portland and Westbrook are usually better."},
    {"slug": "baltimore", "name": "Baltimore", "state": "maryland", "zip": "21201", "nearby": "Towson, Glen Burnie",
     "tip_es": "Inner Harbor es caro. Towson y Glen Burnie tienen Wawa y Royal Farms más baratos.",
     "tip_en": "Inner Harbor is expensive. Towson and Glen Burnie have cheaper Wawa and Royal Farms."},
    {"slug": "boston", "name": "Boston", "state": "massachusetts", "zip": "02108", "nearby": "Quincy, Cambridge, Waltham",
     "tip_es": "Downtown es de los más caros de New England. Quincy o Waltham suelen salvar el tanque.",
     "tip_en": "Downtown is among New England’s priciest. Quincy or Waltham often save the tank."},
    {"slug": "detroit", "name": "Detroit", "state": "michigan", "zip": "48226", "nearby": "Dearborn, Warren",
     "tip_es": "Downtown y el aeropuerto DTW suben el precio. Dearborn y Warren suelen estar mejor.",
     "tip_en": "Downtown and DTW lift the price. Dearborn and Warren are usually better."},
    {"slug": "grand-rapids", "name": "Grand Rapids", "state": "michigan", "zip": "49503", "nearby": "Wyoming MI, Kentwood",
     "tip_es": "Meijer y Costco en los suburbios suelen ganar al centro.",
     "tip_en": "Suburban Meijer and Costco usually beat downtown."},
    {"slug": "minneapolis", "name": "Minneapolis", "state": "minnesota", "zip": "55401", "nearby": "St. Paul, Bloomington",
     "tip_es": "Evita MSP. Bloomington y los suburbios del sur tienen Holiday y Costco más baratos.",
     "tip_en": "Skip MSP. Bloomington and the south suburbs have cheaper Holiday and Costco."},
    {"slug": "jackson", "name": "Jackson", "state": "mississippi", "zip": "39201", "nearby": "Pearl, Ridgeland",
     "tip_es": "De las capitales más baratas del Sur. Pearl y Ridgeland tienen Murphy fuerte.",
     "tip_en": "One of the South’s cheapest capitals. Pearl and Ridgeland have strong Murphy."},
    {"slug": "kansas-city", "name": "Kansas City", "state": "missouri", "zip": "64106", "nearby": "Independence, Overland Park",
     "tip_es": "Compara el lado de Missouri y el de Kansas. Overland Park (KS) suele ganar.",
     "tip_en": "Compare the Missouri and Kansas sides. Overland Park (KS) usually wins."},
    {"slug": "st-louis", "name": "St. Louis", "state": "missouri", "zip": "63101", "nearby": "Clayton, Florissant",
     "tip_es": "Downtown y el arco son caros. El condado y Illinois al otro lado del río suelen estar mejor.",
     "tip_en": "Downtown and the Arch are expensive. The county and Illinois across the river are often better."},
    {"slug": "billings", "name": "Billings", "state": "montana", "zip": "59101", "nearby": "Laurel",
     "tip_es": "La ciudad más grande de Montana. I-90 suele tener mejor precio que el centro.",
     "tip_en": "Montana’s largest city. I-90 is usually cheaper than downtown."},
    {"slug": "omaha", "name": "Omaha", "state": "nebraska", "zip": "68102", "nearby": "Council Bluffs, Bellevue",
     "tip_es": "Council Bluffs (Iowa) a veces gana por unos centavos. Compara los dos lados del río.",
     "tip_en": "Council Bluffs (Iowa) sometimes wins by a few cents. Compare both sides of the river."},
    {"slug": "las-vegas", "name": "Las Vegas", "state": "nevada", "zip": "89101", "nearby": "Henderson, North Las Vegas",
     "tip_es": "El Strip es de lo más caro del oeste. Henderson y North Las Vegas suelen estar 20–40¢ abajo.",
     "tip_en": "The Strip is among the West’s priciest. Henderson and North Las Vegas are often 20–40¢ lower."},
    {"slug": "reno", "name": "Reno", "state": "nevada", "zip": "89431", "nearby": "Sparks",
     "tip_es": "89431 es de los ZIP más usados en GasRadar. Sparks suele estar un poco más barato que el downtown.",
     "tip_en": "89431 is one of GasRadar’s most-used ZIPs. Sparks is usually a bit cheaper than downtown."},
    {"slug": "manchester", "name": "Manchester", "state": "new-hampshire", "zip": "03101", "nearby": "Nashua",
     "tip_es": "Nashua (cerca de Mass) a veces gana. Compara 10 millas.",
     "tip_en": "Nashua (near Mass) sometimes wins. Compare 10 miles."},
    {"slug": "newark", "name": "Newark", "state": "new-jersey", "zip": "07102", "nearby": "Elizabeth, Jersey City",
     "tip_es": "EWR y el Turnpike son caros. Wawa en los suburbios suele salvar el tanque.",
     "tip_en": "EWR and the Turnpike are expensive. Suburban Wawa often saves the tank."},
    {"slug": "albuquerque", "name": "Albuquerque", "state": "new-mexico", "zip": "87102", "nearby": "Rio Rancho",
     "tip_es": "I-25 e I-40 tienen buena oferta. Rio Rancho suele estar un poco bajo el centro.",
     "tip_en": "I-25 and I-40 have solid options. Rio Rancho is usually a bit under downtown."},
    {"slug": "new-york", "name": "New York", "state": "new-york", "zip": "10001", "nearby": "Jersey City, Yonkers, Queens",
     "tip_es": "Manhattan es de lo más caro de EE.UU. Queens, Bronx o Jersey City suelen estar mucho mejor.",
     "tip_en": "Manhattan is among the most expensive in the USA. Queens, the Bronx, or Jersey City are usually much better."},
    {"slug": "buffalo", "name": "Buffalo", "state": "new-york", "zip": "14202", "nearby": "Cheektowaga, Niagara Falls",
     "tip_es": "Upstate es otro mundo vs NYC. Cheektowaga suele ganar al downtown.",
     "tip_en": "Upstate is a different world from NYC. Cheektowaga usually beats downtown."},
    {"slug": "rochester", "name": "Rochester", "state": "new-york", "zip": "14604", "nearby": "Greece, Irondequoit",
     "tip_es": "Los suburbios (Greece) suelen estar mejor que el centro.",
     "tip_en": "The suburbs (Greece) usually beat downtown."},
    {"slug": "charlotte", "name": "Charlotte", "state": "north-carolina", "zip": "28202", "nearby": "Concord, Gastonia",
     "tip_es": "Uptown y CLT son caros. Concord y Gastonia suelen estar 10–20¢ abajo.",
     "tip_en": "Uptown and CLT are expensive. Concord and Gastonia are often 10–20¢ lower."},
    {"slug": "raleigh", "name": "Raleigh", "state": "north-carolina", "zip": "27601", "nearby": "Durham, Cary",
     "tip_es": "Cary y Durham suelen ganar al downtown de Raleigh.",
     "tip_en": "Cary and Durham usually beat downtown Raleigh."},
    {"slug": "fargo", "name": "Fargo", "state": "north-dakota", "zip": "58102", "nearby": "Moorhead",
     "tip_es": "Moorhead (Minnesota) está al otro lado del río: compara los dos.",
     "tip_en": "Moorhead (Minnesota) is across the river—compare both."},
    {"slug": "columbus", "name": "Columbus", "state": "ohio", "zip": "43215", "nearby": "Dublin, Grove City",
     "tip_es": "Downtown y el campus suben el precio. Grove City y el oeste suelen estar mejor.",
     "tip_en": "Downtown and campus lift the price. Grove City and the west side are usually better."},
    {"slug": "cleveland", "name": "Cleveland", "state": "ohio", "zip": "44113", "nearby": "Parma, Lakewood",
     "tip_es": "GetGo y Speedway en Parma suelen ganar al downtown.",
     "tip_en": "GetGo and Speedway in Parma usually beat downtown."},
    {"slug": "cincinnati", "name": "Cincinnati", "state": "ohio", "zip": "45202", "nearby": "Covington, Norwood",
     "tip_es": "A veces Kentucky (Covington) gana por unos centavos. Compara el río.",
     "tip_en": "Kentucky (Covington) sometimes wins by a few cents. Compare across the river."},
    {"slug": "oklahoma-city", "name": "Oklahoma City", "state": "oklahoma", "zip": "73102", "nearby": "Norman, Edmond",
     "tip_es": "QuikTrip en cada esquina. Edmond y el sur suelen estar un poco bajo el centro.",
     "tip_en": "QuikTrip on every corner. Edmond and the south side are usually a bit under downtown."},
    {"slug": "tulsa", "name": "Tulsa", "state": "oklahoma", "zip": "74103", "nearby": "Broken Arrow",
     "tip_es": "Broken Arrow suele estar igual o más barato que el downtown.",
     "tip_en": "Broken Arrow is usually equal or cheaper than downtown."},
    {"slug": "portland", "name": "Portland", "state": "oregon", "zip": "97201", "nearby": "Beaverton, Gresham",
     "tip_es": "Sin self-service. Beaverton y Gresham suelen estar mejor que el centro.",
     "tip_en": "No self-serve. Beaverton and Gresham usually beat downtown."},
    {"slug": "philadelphia", "name": "Philadelphia", "state": "pennsylvania", "zip": "19107", "nearby": "Camden, King of Prussia",
     "tip_es": "Center City es caro. Wawa en los suburbios o Jersey (Camden) suele ganar.",
     "tip_en": "Center City is expensive. Suburban Wawa or Jersey (Camden) usually wins."},
    {"slug": "pittsburgh", "name": "Pittsburgh", "state": "pennsylvania", "zip": "15222", "nearby": "Monroeville, Cranberry",
     "tip_es": "Sheetz en los suburbios suele estar 10–20¢ bajo el downtown.",
     "tip_en": "Suburban Sheetz is often 10–20¢ under downtown."},
    {"slug": "providence", "name": "Providence", "state": "rhode-island", "zip": "02903", "nearby": "Warwick, Pawtucket",
     "tip_es": "Estado chico: Warwick o cruzar a Massachusetts a veces salva 10¢.",
     "tip_en": "Tiny state: Warwick or crossing into Massachusetts sometimes saves 10¢."},
    {"slug": "columbia", "name": "Columbia", "state": "south-carolina", "zip": "29201", "nearby": "Lexington SC",
     "tip_es": "El interior es más barato que Charleston. Lexington suele ganar al centro.",
     "tip_en": "Inland is cheaper than Charleston. Lexington usually beats downtown."},
    {"slug": "charleston", "name": "Charleston", "state": "south-carolina", "zip": "29401", "nearby": "North Charleston",
     "tip_es": "El histórico es caro. North Charleston suele estar mucho mejor.",
     "tip_en": "The historic core is expensive. North Charleston is usually much better."},
    {"slug": "sioux-falls", "name": "Sioux Falls", "state": "south-dakota", "zip": "57104", "nearby": "Brandon SD",
     "tip_es": "I-29 e I-90 tienen truck stops baratos. El centro no siempre gana.",
     "tip_en": "I-29 and I-90 have cheap truck stops. Downtown doesn’t always win."},
    {"slug": "nashville", "name": "Nashville", "state": "tennessee", "zip": "37203", "nearby": "Murfreesboro, Franklin",
     "tip_es": "Downtown y Broadway son una trampa. Murfreesboro y el este suelen estar mejor.",
     "tip_en": "Downtown and Broadway are a trap. Murfreesboro and the east side are usually better."},
    {"slug": "memphis", "name": "Memphis", "state": "tennessee", "zip": "38103", "nearby": "Bartlett, Southaven",
     "tip_es": "Southaven (Mississippi) a veces gana. Compara el condado, no solo el centro.",
     "tip_en": "Southaven (Mississippi) sometimes wins. Compare the county, not just downtown."},
    {"slug": "houston", "name": "Houston", "state": "texas", "zip": "77002", "nearby": "Katy, Pasadena, The Woodlands",
     "tip_es": "Downtown e IAH son caros. Katy, Pasadena y el suroeste suelen estar 15–30¢ abajo.",
     "tip_en": "Downtown and IAH are expensive. Katy, Pasadena, and the southwest are often 15–30¢ lower."},
    {"slug": "dallas", "name": "Dallas", "state": "texas", "zip": "75201", "nearby": "Arlington, Plano, Irving",
     "tip_es": "Downtown y Love Field suben el precio. Plano, Irving y Arlington suelen ganar.",
     "tip_en": "Downtown and Love Field lift the price. Plano, Irving, and Arlington usually win."},
    {"slug": "san-antonio", "name": "San Antonio", "state": "texas", "zip": "78205", "nearby": "New Braunfels, Schertz",
     "tip_es": "El River Walk es caro. H-E-B y Costco en el norte suelen estar mejor.",
     "tip_en": "The River Walk is expensive. H-E-B and Costco on the north side are usually better."},
    {"slug": "austin", "name": "Austin", "state": "texas", "zip": "78701", "nearby": "Round Rock, Pflugerville",
     "tip_es": "Downtown y el aeropuerto AUS son caros. Round Rock suele estar más barato.",
     "tip_en": "Downtown and AUS are expensive. Round Rock is usually cheaper."},
    {"slug": "el-paso", "name": "El Paso", "state": "texas", "zip": "79905", "nearby": "Las Cruces, Socorro",
     "tip_es": "79905 es de los ZIP más usados en GasRadar. Compara el este de la ciudad, no solo el centro.",
     "tip_en": "79905 is one of GasRadar’s most-used ZIPs. Compare the east side, not just downtown."},
    {"slug": "fort-worth", "name": "Fort Worth", "state": "texas", "zip": "76102", "nearby": "Arlington, Dallas",
     "tip_es": "Menos caro que Dallas downtown. Arlington en el medio suele tener buena competencia.",
     "tip_en": "Cheaper than downtown Dallas. Arlington in the middle usually has solid competition."},
    {"slug": "salt-lake-city", "name": "Salt Lake City", "state": "utah", "zip": "84101", "nearby": "West Valley, Sandy",
     "tip_es": "Maverik y Costco en West Valley suelen ganar al downtown.",
     "tip_en": "Maverik and Costco in West Valley usually beat downtown."},
    {"slug": "burlington", "name": "Burlington", "state": "vermont", "zip": "05401", "nearby": "South Burlington, Winooski",
     "tip_es": "South Burlington suele estar mejor que el centro junto al lago.",
     "tip_en": "South Burlington is usually better than the lakeside downtown."},
    {"slug": "richmond", "name": "Richmond", "state": "virginia", "zip": "23219", "nearby": "Henrico, Chesterfield",
     "tip_es": "Henrico y Chesterfield suelen estar 10–20¢ bajo el downtown.",
     "tip_en": "Henrico and Chesterfield are often 10–20¢ under downtown."},
    {"slug": "virginia-beach", "name": "Virginia Beach", "state": "virginia", "zip": "23451", "nearby": "Norfolk, Chesapeake",
     "tip_es": "La playa es cara. Chesapeake y Norfolk inland suelen estar mejor.",
     "tip_en": "The oceanfront is expensive. Inland Chesapeake and Norfolk are usually better."},
    {"slug": "arlington", "name": "Arlington", "state": "virginia", "zip": "22201", "nearby": "Alexandria, Washington",
     "tip_es": "Más barato que D.C., pero sigue siendo Norte de Virginia. Compara Alexandria y Fairfax.",
     "tip_en": "Cheaper than D.C., but still Northern Virginia. Compare Alexandria and Fairfax."},
    {"slug": "seattle", "name": "Seattle", "state": "washington", "zip": "98101", "nearby": "Bellevue, Tacoma",
     "tip_es": "Downtown y Sea-Tac son caros. Tacoma o el sur suelen estar mejor que Bellevue.",
     "tip_en": "Downtown and Sea-Tac are expensive. Tacoma or the south side often beat Bellevue."},
    {"slug": "spokane", "name": "Spokane", "state": "washington", "zip": "99201", "nearby": "Spokane Valley",
     "tip_es": "Más barato que Seattle. Spokane Valley suele ganar al centro.",
     "tip_en": "Cheaper than Seattle. Spokane Valley usually beats downtown."},
    {"slug": "charleston-wv", "name": "Charleston", "state": "west-virginia", "zip": "25301", "nearby": "South Charleston",
     "tip_es": "Sheetz es la referencia. South Charleston suele estar un poco bajo el centro.",
     "tip_en": "Sheetz is the benchmark. South Charleston is usually a bit under downtown."},
    {"slug": "milwaukee", "name": "Milwaukee", "state": "wisconsin", "zip": "53202", "nearby": "Waukesha, West Allis",
     "tip_es": "Kwik Trip en West Allis o Waukesha suele ganar al downtown.",
     "tip_en": "Kwik Trip in West Allis or Waukesha usually beats downtown."},
    {"slug": "madison", "name": "Madison", "state": "wisconsin", "zip": "53703", "nearby": "Fitchburg, Sun Prairie",
     "tip_es": "El campus sube el centro. Sun Prairie suele estar más barato.",
     "tip_en": "Campus lifts downtown. Sun Prairie is usually cheaper."},
    {"slug": "cheyenne", "name": "Cheyenne", "state": "wyoming", "zip": "82001", "nearby": "Fort Collins",
     "tip_es": "I-80 e I-25 tienen truck stops baratos. A veces Fort Collins (Colorado) vale la pena comparar.",
     "tip_en": "I-80 and I-25 have cheap truck stops. Sometimes Fort Collins (Colorado) is worth comparing."},
]

BAND_ES = {
    "bajo": "por debajo del promedio nacional",
    "medio": "cerca del promedio nacional",
    "alto": "por encima del promedio nacional",
}
BAND_EN = {
    "bajo": "below the national average",
    "medio": "near the national average",
    "alto": "above the national average",
}
